<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

   <title>Система статистики</title>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="css/base.css" rel="stylesheet" media="all">
 </head>

  <body>

<h2>Список url-ов</h2>

<?php if(count($this->records) >0):?>
<table>
    <tr><th>id</th><th>ip</th><th>url</th><th>comment</th><th>created</th></tr>
<?php foreach($this->records as $record): ?>
    <tr>
        <td><?php echo $record['id'] ?></td>
        <td><?php echo $record['ip'] ?></td>
        <td><?php echo $record['url'] ?></td>
        <td><?php echo $record['comment'] ?></td>
        <td><?php echo $record['created_at'] ?></td>
    </tr>
<?php endforeach ?>
</table>
<?php else: ?>
<p>нет данных для отображения!</p>
<?php endif ?>

  </body>
</html>