<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

   <title>тестовая страничка</title>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="css/base.css" rel="stylesheet" media="all">
 </head>

  <body>

<script src="/js/jquery-1.7.1.min.js"></script>  <!--сей скрипт надо к банеру приделывать-->
<script>
    $(document).ready(function(){
        $.ajax({
          type: "POST",
          url: "?page=setStat",//сюда комент к банеру можно приделать
          data: "comment=test_comment",
          success: function(respons){ //просто для тестирования
            alert( "ответ сервера: " + respons );
          }
        });
    });
</script>
<p>тут типа картинка должна быть</p>
  </body>
</html>